nextcloud/news-android

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ssl/MemorizingTrustManager.java

The current implementation first checks the appTrustManager, and prints a stack trace even if the certificate is valid using the system key store.
I think it makes more sense to first check the certificate using the defaultTrustManager and if that fails check using the appTrustManager.

First try defaultTrustManager, then appTrustManager

---

News-Android-App/src/main/assets/web.css

Remove margin from specific tags and move margin to #content div.
Using max-width: 100% and adding a margin can lead to the element exceeding the width of the container.

Fix images being bigger than DetailFragment width.

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/NewsListRecyclerAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/ViewHolder.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/events/podcast/PodcastCompletedEvent.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/model/MediaItem.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/model/PodcastItem.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/model/TTSItem.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastDownloadService.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastPlaybackService.java
News-Android-App/src/main/res/drawable/newsreader_playpause.xml
News-Android-App/src/main/res/drawable/newsreader_playpause_light.xml
News-Android-App/src/main/res/layout/subscription_detail_list_item_extended.xml
News-Android-App/src/main/res/layout/subscription_detail_list_item_podcast_wrapper.xml
News-Android-App/src/main/res/values/attrs.xml
News-Android-App/src/main/res/values/themes.xml

Some fixes and improvements:
* Fixes a NPE when starting a podcast while the podcast service is already running
* Move more UI stuff into the ViewHolder
* Stop the PodcastPlaybackService when not playing anything (similar to OwncloudSyncService)
* Use Drawables for the play/pause button instead of Drawable states, turns out this is more reliable. This now uses Drawable tinting to adapt to the light/dark theme.
* Remove the Podcast elements from the UI when the Podcast/TTS is finished. (Collapse the PodcastFragment and remove the slider from the bottom)

Podcast fixes

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java
News-Android-App/src/main/res/values/attrs.xml
News-Android-App/src/main/res/values/colors.xml
News-Android-App/src/main/res/values/themes.xml

This change is only visible while the content is still loading.
Fixes #426.

Set news detail view's background color according to theme.

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java
News-Android-App/src/main/res/layout/fragment_dialog_image.xml
News-Android-App/src/main/res/values-cs-rCZ/strings.xml
News-Android-App/src/main/res/values-fi-rFI/strings.xml
News-Android-App/src/main/res/values-fr/strings.xml
News-Android-App/src/main/res/values-it/strings.xml
News-Android-App/src/main/res/values-ja-rJP/strings.xml
News-Android-App/src/main/res/values-nl/strings.xml
News-Android-App/src/main/res/values-pt-rBR/strings.xml
News-Android-App/src/main/res/values-pt-rPT/strings.xml
News-Android-App/src/main/res/values-sq/strings.xml
News-Android-App/src/main/res/values/strings.xml

* improved layout of the contextDialog (margins/paddings) (see screenshots below)
* omit alt-text from dialog if empty or same as imagename (see screenshots below)
* hide the dialog immediately after "Download Image" pressed (dismiss on download-success/error)
* refactored all UI-strings to strings.xml for better internationalization
* gain control over sort-order of dialog-list-items (HashMap -> LinkedHashMap). Now, order is order of insertion (`mMenuItems.put(xyz)`), was not the case with `mMenuItems = HashMap``
* Fixed bug where app crashes when certain relative image-links appear on a website viewed in internal browser (e.g. on heise-website)
* Colors of dialog and items do not follow the different themes (dark/light) correctly.
(Should it??? the OptionsMenu (top-right) also stays …

ui and ux enhancements regarding NewsDetail-ContextDialog

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java
News-Android-App/src/main/res/values/styles.xml

Removed API21-styles from ImageDialog. Reverted to AppTheme.
Fixes #448

Removed API21-styles from ImageDialog. Reverted to AppTheme.

---

News-Android-App/src/main/res/layout/activity_new_feed.xml
News-Android-App/src/main/res/layout/fragment_dialog_image.xml
News-Android-App/src/main/res/layout/fragment_podcast.xml
News-Android-App/src/main/res/layout/podcast_feed_row.xml
News-Android-App/src/main/res/layout/podcast_row.xml
News-Android-App/src/main/res/layout/widget_item.xml
News-Android-App/src/main/res/menu/news_reader.xml
News-Android-App/src/main/res/values/strings.xml

There was hardcoded text left in some layouts. I pulled it into strings.xml so it can be translated or marked it with the ```tools``` prefix when it's just used for the layout view inside Android Studio.

Android lint fixes

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java

Fixed https://github.com/owncloud/News-Android-App/issues/387 (design issue - Low contrast on Settings)
Sets text- and iconcolor of Settings-ActionBar to white in code, as this should not be controlled by the selected theme. (text/icon should remain white in dark AND light theme)
before    <–>   after

Fixed #387 - Settings-actionbar text color

---

News-Android-App/src/main/res/values-pt-rBR/strings.xml
News-Android-App/src/main/res/values/strings.xml

They will no longer be displayed inside transifex.
The build just broke because @null has been translated (which references a resource). This should be fixed inside transifex too so the error doesn't get imported again.

Excluded value arrays and references to resources from translation.

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java

Because we got many bug reports because of the broken mobile redirect. I see no security issues in enabling the web storage api.
Fixes #468, #466, #385, #471

Enabled web storage inside webview to fix mobile redirect at heise.de

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/SubscriptionExpandableListAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/interfaces/ExpListTextClicked.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/HttpJsonRequest.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/InsertIntoDatabase.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/owncloud/InsertFeedIntoDatabase.java
News-Android-App/src/main/res/layout/fragment_dialog_feedoptions.xml
News-Android-App/src/main/res/values/strings.xml

See Issue #455
Longpress on a Feed(source) opens up NewsReaderListDialogFragment:
Here you can select to **rename** or **remove** the selected feed.
The code first tries to propagate the change (rename/remove) to the server (JSON-Request), 
- upon success, the local db is updated accordingly so that the following sync performs smoothly
- upon failure, no local change is made and an error message is shown.
Tested it for several weeks now without any problems.
Note:
Because the "Feedurl" was not in the local db in previous versions, it may happen, that the Feed's Url is not shown in the DialogFragment's subtitle-line! The Feedurl initially gets synced to the device when a feed has new items, or for all feeds at once, when you do a app data removal and resync. Once every feed got updated, …

New Feature: Rename and remove feeds

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java
News-Android-App/src/main/res/values/styles.xml

Removed API21-styles from all DialogFragments. Reverted to AppTheme.
(NewsDetailImageDialogFragment and NewsReaderListDialogFragment)
https://github.com/owncloud/News-Android-App/commit/1f1b06f96ba97e52ae6bc5086e2db78d85c298e8#commitcomment-15337011

fix theme of all dialogFragments

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java

- Fixes a small bug with the NewsDetailImageDialogFragment:
- —> Longpress > "Download Image" on Image1
- —> Longpress on Image2 before Image1 finished downloading
- —> Dismiss dialog of Image2 (through clicking outside the dialog)
- —> **BUG:** The dialog of Image1 appears again
- Fixed Typo (Cipboard > Clipboard)
- Removed unused method in NewsDetailFragment
- other small optimizations

Optimize NewsDetailImageDialogFragment

---

News-Android-App/src/main/AndroidManifest.xml

Some websites like youtube offer rss but don't name it *.rss or *.atom.xml
So this small change on the AndroidManifest will make thous sites also support such rss links.

accept more rss urls

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/di/ApiProvider.java

Fixes some issues related to the Android Account Manager. Uses a custom Auth-Dialog instead of the build-in authentication manager dialog.
Details: https://github.com/nextcloud/Android-SingleSignOn/issues/30

add support for auth via custom auth manager

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java
News-Android-App/src/main/res/xml/pref_empty.xml

It is not the most beautiful fix ever, but appears to work...

#688 - show section heading of first/general settings section in simple preferences view

---

News-Android-App/src/debug/AndroidManifest.xml
News-Android-App/src/main/AndroidManifest.xml
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java
News-Android-App/src/main/res/layout-sw600dp-land/activity_newsreader.xml
News-Android-App/src/main/res/layout/activity_authenticator.xml
News-Android-App/src/main/res/layout/activity_new_feed.xml
News-Android-App/src/main/res/layout/activity_news_detail.xml
News-Android-App/src/main/res/layout/activity_newsreader.xml
News-Android-App/src/main/res/layout/activity_sync_interval_selector.xml
News-Android-App/src/main/res/layout/fragment_dialog_feedoptions.xml
News-Android-App/src/main/res/layout/fragment_dialog_image.xml
News-Android-App/src/main/res/layout/fragment_sync_interval_selector.xml
News-Android-App/src/main/res/values-night/colors.xml
News-Android-App/src/main/res/values/attrs.xml
News-Android-App/src/main/res/values/colors.xml
News-Android-App/src/main/res/values/themes.xml

This change does three things:
1. explicitly define a SplashScreen theme, in addition to the base AppTheme
2. use that SplashScreen theme in the app manifest
3. on creation of the main Activity, change theme to base AppTheme (= get rid of Splash background)
(4. tidy up manual color setting in SettingsActivity)

#693 - fix SettingsActivity background

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/VersionInfoDialogFragment.java
News-Android-App/src/main/res/layout/dialog_version_info.xml
News-Android-App/src/main/res/menu/news_reader.xml
News-Android-App/src/main/res/values/strings.xml
News-Android-App/src/main/res/xml/pref_about.xml
News-Android-App/src/main/res/xml/pref_headers.xml

@David-Development this is a proposal about how the About/changelog thing could be addressed - this is mirroring what the Nextcloud app guys are doing:
In the settings activity, there is a new header/section for about-stuff now.
One issue: I could not yet figure out how to show a dialog when tapping on the app name/version entry - this would be a good point to pop up the changelog dialog (SettingsActivity line 222, for example).
What do you think in general?

704 - move about dialog info to settings menu

---

News-Android-App/src/main/AndroidManifest.xml
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderApplication.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/OwnCloudSyncAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/ForegroundListener.java

Based on https://stackoverflow.com/a/41307616
As far as I understand [getRunningTasks](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningTasks(int)) will return our news app on API 21+ if user is in another app (not home screen).
I didn't validate this but the new approach doesn't need additional permissions and it works reliable, consistent across API versions (tested on minSdk 17 and 25).

Rework foreground detection

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ssl/OkHttpSSLClient.java

As discussed https://github.com/nextcloud/Android-SingleSignOn/commit/e781a33e0115ab8c3f4983fed2def1ab924fb9d9#commitcomment-32973039

Downgrade okhttp to 3.12.2 and use same version for all okhttp deps

---

.circleci/config.yml
News-Android-App/build.gradle

auto-value is not used in our code and stripped by proguard anyway.
Just as a reminder: This would be the right time to enable CircleCI so we won't break any of these tests again.

exclude auto-value from apk to fix lint error

---

News-Android-App/build.gradle

It's included in dagger-compiler since version 2.12
https://github.com/google/dagger/commit/772374b9716e34a463a517222adbfcb678e4fb72
Signed-off-by: Unpublished <unpublished@gmx.net>

Bump dagger from 2.16 to 2.22.1 and remove jsr250-api

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java

This PR fixes the bug described in issue #784. Can it be merged or should this be handled differently?

#784: Fix first entry not marked as read after sync

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java

Opening an article in browser was handled differently in different views.
- When a link was pressed in the webview showing the article, the users browser settings were considered and the correct browser opened
- When a link was opened using the menu entry, the article was always loaded in Chrome custom tabs, independend of user settings.
Both ways now use the same function and behaviour.

Fixed open article in browser call

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/ThemeChooser.java

Fixes #804
On a side note, the docs state that [MODE_NIGHT_AUTO_TIME is deprecated](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate.html#MODE_NIGHT_AUTO_TIME) in favor of [MODE_NIGHT_AUTO_BATTERY](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate.html#MODE_NIGHT_AUTO_TIME). I could also address that here if it's something you want to fix, otherwise I'll leave it as-is.
Signed-off-by: William Brawner <me@wbrawner.com>

Use system light/dark theme setting for Android 10+

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsFragment.java
News-Android-App/src/main/res/xml/pref_about.xml
build.gradle

Adds debug information before opening the GitHub website. It'll automatically fill out the bug report with additional information such as app version and app settings. Therefore it makes debugging for us easier. 
@stefan-niedermann @desperateCoder maybe this is helpful for you as well?
The following example shows which settings I include in bug reports for the news app. 
```
Please describe your bug here...
---
App Version: 0.9.9.30
App Version Code: 146
---
SSO enabled: true
---
OS Version: 4.14.112+(5891938)
OS API Level: 29
Device: generic_x86
Model (and Product): Android SDK built for x86 (sdk_gphone_x86)
---
sp_max_cache_size=500
sp_swipe_left_action=2
sw_use_single_sign_on=true
cb_ShowOnlyUnread=false
cb_openInBrowserDirectly=false
lv_cacheImagesOffline=0
cb_AutoSyncOnStart=false …
```

update gradle / add debug information to github issue

---

News-Android-App/src/main/assets/web.css

sometimes tables are too wide and cause the detail view to be horizontally scrollable.

fix tables are too wide

---

.github/workflows/ci.yml
.github/workflows/gradle-wrapper-validation.yml
News-Android-App/build.gradle
News-Android-App/src/dev/res/drawable/ic_launcher_foreground.xml
README.md

This PR enables a CI-build for the News android app.
@David-Development your choice whether or not you want to go this way, but i have made positive experiences only while i migrated Notes and Deck to GitHub Actions.
- Better integration without leaving the GitHub UI
- Much better performance
- You can access a dev-build artifact for each build (and install it beside a released version)
- Everyone who forks this project on GitHub has automatically CI without the need to configure a 3rd-party service
Interested?

Android actions ci

---

News-Android-App/src/main/res/drawable/custom_progress.xml

Hi,
I found there is a compatibility issue in the progress bar.
According to [this discussion](https://stackoverflow.com/questions/26532382/progressbar-circle-shows-no-progress-on-android-l-api-21), the default value for android:useLevel under the tag incorrectly changed to false in the L Preview build. Therefore you should add **android:useLevel="true"** in the shape element.
Here is the behavior between API 21 and 27.
API 27
API 21
Note that the progress bar will always be full no matter what the progress value set to it.
This pull request help you fix this problem, thanks for your attention.

Fix issues on API Level 21

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java

I noticed that regardless of the browser preferences (built-in, Custom Tabs or external) when skipping the detail view, the external browser is always used.
Therefore I copied the preference check from the detail view fragment to the list activity to open the custom tabs when they are selected in the  preferences (I stripped out the built-in browser because it only works inside the detail view)

Custom Tabs when skipping detailed view

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderApplication.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties

:warning: This PR also raises the `minSdk` from `17` to `18`. This shouldn't be an issue because the Files app has already `minSdk = 19`.
This enables the following features fully backward compatible:
- Sequential streams (java.util.stream)
- A subset of java.time
- java.util.function
- Recent additions to java.util.{Map,Collection,Comparator}
- Optionals (java.util.Optional, java.util.OptionalInt and java.util.OptionalDouble) and some other new classes useful with the above APIs
- Some additions to java.util.concurrent.atomic (new methods on AtomicInteger, AtomicLong and AtomicReference)
- ConcurrentHashMap (with bug fixes for Android 5.0)
Fore more information see https://developer.android.com/studio/write/java8-support

Enable core library desugaring

---

News-Android-App/src/main/res/values-night/colors.xml

- Use a more neutral grey for the sidebar
- Remove customized dark flavor of the "Nextcloud blue" (won't matter anyway after https://github.com/nextcloud/news-android/issues/642 has been implemented)
1. old (current `master`)
2. new (changes from this PR)
3. files app for comparison 
1 | 2 | 3
--- | --- | ---

Use neutral grey for sidebar background in dark mode

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderApplication.java

After [raising the `minSdk` to `21`](https://github.com/nextcloud/news-android/pull/951), it is no longer necessary to include `multidex` support explicitly.
Starting with Android 5, it is supported out of the box → Removing it will reduce the size of the compiled app and reduce the compile time.

Remove multidex

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java
News-Android-App/src/main/res/values/strings.xml

While working on #952 i realized that the used `MaterialFilePicker` and its forks aren't maintained well and don't work flawlessly in version `1.9.1+`.
I therefore suggest to remove this dependency completely and use the native system file picker for selecting an `.opml` file.
Another advantage is that starting with `targetSdk=30` the current implementation will probably break anyway because of the introduction of [scoped storage](https://developer.android.com/about/versions/11/privacy/storage).
Last but not least the native system file picker solution will allow to directly pick files from document providers like Nextcloud without the need of having the file available offline on the device.

Use native system file picker for OPML import

---

News-Android-App/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

> Starting in version 4.2, AGP will use the Java 8 language level by default. ([Source](https://developer.android.com/studio/releases/gradle-plugin#java-8-default))
Follow-Up to #965

Bump gradle to 6.7, AGP to 4.2.1 and remove explicit Java 8 declaration

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
News-Android-App/src/main/res/layout/empty_content_view.xml
News-Android-App/src/main/res/layout/fragment_newsreader_detail.xml
News-Android-App/src/main/res/values-night/colors.xml
News-Android-App/src/main/res/values/colors.xml
News-Android-App/src/main/res/values/dimens.xml
News-Android-App/src/main/res/values/strings.xml

Fixes #824
- Adds logo
- Uses bigger font size
- Adds call to action text ("pull down 2 refresh") 
- Aligns this view with Deck & Notes
| _ | _ |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/4741199/122589320-65e6e280-d060-11eb-9dfc-55d96f67878f.png) | ![after](https://user-images.githubusercontent.com/4741199/122589336-6b442d00-d060-11eb-98e3-d33279dbdf01.png) |

Enhance empty content view

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/ThemeUtils.java
News-Android-App/src/main/res/values/strings.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- Upgrade to **Java 11**
- Enables new features (See [Java 10](https://www.baeldung.com/java-10-overview) and [Java 11](https://www.baeldung.com/java-11-new-features)) like
- `var` keywords
- new String methods (for example `"".lines()` or `"".isBlank()`)
- new Collection methods (for example `list.toArray(...)`)
- extended support for type inference
- Upgrade to **AGP 7.0.0**
- Requires Android Studio Arctic Fox AFAIK, [released yesterday](https://android-developers.googleblog.com/2021/07/android-studio-arctic-fox-202031-stable.html).
- Upgrade to **minSdk 30**
- Required for Play Store [starting August](https://developer.android.com/distribute/best-practices/develop/target-sdk).
- Add `falcon:2.2.0` explicitly, because `screengrab:2.1.0` relies on `falcon:2.1.1` which is not available …

Bump Java, AGP & minSdk 🥳

---

security/GHSL-2021-1033_Nextcloud_News_for_Android.md

When I wrote this advisory, I made a typo in the `FLAG_GRANT_*_URI_PERMISSION` flags. This is a small PR to fix that.

Fix flag names in advisory GHSL-2021-1033

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/OwnCloudSyncAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java

Related to #1075. 
Because greenDAO has internal caching for the current session, there have been out-of-date data issues when fetching RSS items from the DB. This is because `RssItem` and `Feed` entities already have their own internal caching for "many-to-one" and "one-to-many" relationships. There were three ways out of the situation:
1. Completely remove relationship caching in entities
2. Use `RssItemDao#deepQuery()`, but this limits greenDAO's query flexibility
3. Clear session cache after synchronization
I think option (3) is the best option in this case, because it affects all entities at once, not just `RssItem`, and we don't violate or interfere with the original entity caching logic, which would have to be removed. Option (2) requires the use of a similar method in `Feed` and …

Delete cached entities to keep entity relationships up to date

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java
News-Android-App/src/main/res/values-de/strings.xml
News-Android-App/src/main/res/values/strings.xml
News-Android-App/src/main/res/xml/pref_display.xml

This PR adds support for optionally playing podcasts in an external app.
Closes #1094 
I'm not really happy with the special casing needed here to handle the different MediaItem types and downloaded podcasts, but it does seem to work.

External player support

---

News-Android-App/src/main/AndroidManifest.xml
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PiPVideoPlaybackActivity.java

Especially
`/home/runner/work/news-android/news-android/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/DownloadImagesService.java:145: Error: When targeting Android 13 or higher, posting a permission requires holding the POST_NOTIFICATIONS permission [NotificationPermission]`
sounds like it should be fixed before publishing.
Haven't had a chance to test PiP mode, so please check if it still works as expected.

Fix lint errors

---

.github/workflows/ci.yml

This shoud avoid running CI for PRs which originate from this repo where CI is already run via push.
Should fix failing checks for dependabot PRs this way.
edit: Looks working 👍

Avoid running ci two times

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java

Fixes #1182 and maybe other podcast control visibility related issues.
This preserves original motivation of commenting out the `collapsePodcastView` call, see #1053

Collapse podcast view if playback is not initialized

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/notification/NextcloudNotificationManager.java

Avoids unnecessarily querying db

Bail out early on generating unread rss items notifications

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/di/ApiProvider.java

- removed deprecated api calls
- updated sso lib to 0.8.0
- fix bug where login activity is launched twice

SSO lib updates

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java
docker-nextcloud-test-instances/README.md
docker-nextcloud-test-instances/docker-compose.yaml

- Implements OnRequestPermissionsResultCallback and automatically triggers import/export again after required permission has been granted
- Uses new MediaStore API for Android 11 and above (which doesn't require permission dialog anymore)
- Autoformatted code..
Closes https://github.com/nextcloud/news-android/issues/1188

fix export issues on Android 11 and above

---

News-Android-App/src/main/assets/web.css

This patch adds line-height to h1 tags to remove  text overlap.
Before:
After:

add line-height for h1 tags

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/events/podcast/SeekPodcast.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastPlaybackService.java

created seekpodcast event and fixed podcast seeking

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/res/menu/news_reader.xml

This PR adds a shortcut to "Show only unread articles" in the toolbar.
The shortcut isn't visible when "All unread items" and "Starred items" is open, because they ignore that option.
This was discussed in #1026. 
Screenshot:

Add shortcut to "Show only unread articles" in the toolbar

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/Search.java
News-Android-App/src/main/res/values/strings.xml
News-Android-App/src/main/res/xml/pref_general.xml

This PR adds option `Both` to `Search In`, allowing users to search through both title and body of articles at the same time.  
This closes #1263 
Implementation details:
1. Added private helper function `getSearchSQLForColumn` in `DatabaseConnectionOrm` to reduce code duplication.
2.  Changed `getAllItemsIdsForFolderSQLSearch` to take a list of `columns` to make the function more flexible and to minimize code duplication.
3. Added new string value `pref_general_search_in_both`
_Note: Translations are missing_

Allow searching both title and body at the same time

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java
News-Android-App/src/main/res/layout/fragment_dialog_feedoptions.xml
News-Android-App/src/main/res/values/strings.xml

This adds a "Open-in settings" when long-pressing on a feed, allowing users to specify how a feed is opened.
This _was_ a __draft__ because:
1. ~Internal Browser isn't a option yet.~ This is marked unnecessary as `Chrome-Custom-Tags` is basically the same thing. (see https://github.com/nextcloud/news-android/pull/1266#issuecomment-1733727181) 
2. ~The option isn't persistent. Unsure why, it's stored in the database but it's always read back as `null`?~ This has been fixed thanks to David! (https://github.com/nextcloud/news-android/commit/f850ad2951c01bf52fd1df3238bef926d5e4ed18)
3. ~Unsure what a good tag [here](https://github.com/mkanilsson/news-android/blob/per-feed-open-settings/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java#L313) is.~ …

per-feed open-in settings

---

CHANGELOG.md
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/Constants.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PiPVideoPlaybackActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/VersionInfoDialogFragment.java

When the app is updated the Changelog will be visible on the first app start

show changelog after update of app

---

News-Android-App/src/main/res/layout/activity_login_dialog.xml

I just added invisible hints for the autofill service (see https://developer.android.com/guide/topics/text/autofill-optimize).
This allows password managers and other autofill service to pick up on these input fields and autofill the users credentials.

Enable androids autofill service in login mask

---

News-Android-App/src/main/res/drawable/ic_baseline_account_circle_24.xml

Icon color now matches those of action icons in all themes.
Tested with and without user avatars set in nextcloud.

Fix avatar placeholder renders white on white in light theme

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsFragment.java

Fixes following lint error:
```
/home/runner/actions-runner/_work/news-android/news-android/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsFragment.java:380: Error: Call requires API level 33 (current min is 21): java.net.URLEncoder#encode [NewApi]
body = URLEncoder.encode(debugInfo, StandardCharsets.UTF_8);
~~~~~~
```
Ironically opening a bug report would result in a crash on API version lower than 33.
Introduced with 098fb150dfc64bac893c213dcaabf0b0d83fa24b

Fix lint for URLEncoder.encode which requires API 33

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/model/OcsUser.java
News-Android-App/src/main/res/layout/toolbar_layout.xml
News-Android-App/src/main/res/menu/news_reader.xml

This is just a proof of concept - but I think this fixes the flickering. I tested on API level 26 and 34.
The implementation of the Toolbar is as documented in the [Material Design Components docs](https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md).
The account button is now a menu item and looks and behaves exactly as all other menu icons without further configuration. It is visible between the search icon and the overflow menu icon (if room).
Fixes #1291

Fix flickering toolbar

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java

The values used for selected browser aren't the ones set in strings.xml.
Fixes issue #1289

fix: Typo in selected browser preference usage

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/PodcastArrayAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/SubscriptionExpandableListAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragment.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/RssItemViewHolder.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/NewsFileUtils.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/model/PodcastItem.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastDownloadService.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastPlaybackService.java
News-Android-App/src/main/res/drawable/ic_action_delete_24_theme_aware.xml
News-Android-App/src/main/res/menu/news_detail.xml
News-Android-App/src/main/res/values/strings.xml

This PR adds 1. a trashcan icon in the toolbar when in a podcast and 2. a special `Downloaded Podcasts` in the sidebar.
This is a __draft__ because:
1. The UI doesn't update and adds the trashcan icon when a podcast has been downloaded.
2. I can't manage to get the number of downloaded podcasts to show up in the sidebar.
> NOTE: This is a breaking change which makes users unable to play their already downloaded podcasts, the reasons for this is: Before, the media was stored in `md5_hashed_url/filename` but since sqlite doesn't have a `MD5` function I had to change the path to `rss_item_fingerprint/filename` so I can use a `fingerprint in (ids)` query and get all downloaded podcasts
Once this is done, it will close #742 
https://github.com/nextcloud/news-android/assets/18418792/aa9afc91-99f …

Add "remove podcast" in toolbar and "Downloaded podcasts" special folder

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/SubscriptionExpandableListAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/NewsListRecyclerAdapter.java
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
News-Android-App/src/main/res/values/strings.xml

- Add translatable strings
- Fix bug where app crashes when the user tries to open the "Downloaded podcasts" while a download is running
- Fix bug where "Downloaded podcasts" is not showing in case "Show only unread articles" is selected in the settings.
- Show the number of items in the "Downloaded podcasts" section in the sidebar
- Remove duplicate code due to merging

downloaded podcast refactoring

---

News-Android-App/src/main/assets/web.css

Fix for https://github.com/nextcloud/news-android/issues/1368

hide empty/broken iframes

---

News-Android-App/proguard-rules.pro

This enables obfuscation and adds specific rules to keep things that actually need to be kept.
Apk sizes goes down 8% from 5319kB to 4906kB.
see https://github.com/nextcloud/Android-SingleSignOn/pull/635 for context

Improve proguard-rules.pro

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java

Fixes #1381
According to https://issuetracker.google.com/issues/304335616 `java.util.stream.Stream.toList` is not supported (yet) by desugar library.
Use `java.util.stream.Collectors.toList` instead [which is supported by desugar library](https://developer.android.com/studio/write/java11-default-support-table).

Fix crash in downloaded podcasts below API 34

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/widget/WidgetProvider.java

Otherwise it cannot be updated with fill in data:
https://github.com/nextcloud/news-android/blob/6b6528a2c76012e6f8d69357f7adb25f66ccd64c/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/widget/WidgetNewsViewsFactory.java#L139-L147
Fixes #1035
Fixes #1355

Pending intent template needs to be mutable

---

News-Android-App/proguard-rules.pro

Follow up from: https://github.com/nextcloud/news-android/pull/1435 - sounds like we don't need the GSON rules anymore. I've removed them and tested the debug build without the GSON rules and it seemed to work just fine (we don't use `@SerializedName` because we do the deserialization mostly manually)
> Added default ProGuard / R8 rules ([@​Marcono1234](https://github.com/Marcono1234), [#2397](https://redirect.github.com/google/gson/issues/2397), [#2420](https://redirect.github.com/google/gson/issues/2420); [@​sgjesse](https://github.com/sgjesse), [#2448](https://redirect.github.com/google/gson/issues/2448); [@​sfreilich](https://github.com/sfreilich))
If you are using ProGuard or R8 (for example for Android projects) you might not need any special Gson configuration anymore if your …

cleanup proguard gson rules

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/RssItemToHtmlTask.java

This was a subtle bug caused by formatting css font size values according to the devices locale. This caused the wrong decimal separator to be rendered which could not be interpreted by css. Explicitly pinning formatting to US-format fixes this.

Fix text display too small inside webviews for non English locales #1428

---

News-Android-App/build.gradle
News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListFragment.java
News-Android-App/src/main/res/layout-sw600dp-land/activity_newsreader.xml
News-Android-App/src/main/res/layout/activity_new_feed.xml
News-Android-App/src/main/res/layout/activity_news_detail.xml
News-Android-App/src/main/res/layout/activity_newsreader.xml
News-Android-App/src/main/res/layout/activity_pip_video_playback.xml
News-Android-App/src/main/res/layout/activity_settings.xml
News-Android-App/src/main/res/layout/fragment_newsreader_detail.xml
News-Android-App/src/main/res/layout/fragment_newsreader_list.xml
News-Android-App/src/main/res/layout/toolbar_layout.xml

Since Android 15 (Target SDK 35) Edge-To-Edge is enabled by default.. which breaks the app quite a bit since the AppBars etc.. are hidden behind the status bar because we don't use Compose yet. 
--> https://developer.android.com/develop/ui/views/layout/edge-to-edge
Since it was quite tricky to find a solution for the Podcast Overlay etc.. Positioning them correctly by respecting the insets seems to be somewhat difficult. Therefore, for now I'm just using the `android:fitsSystemWindows="true"` to restore the previous functionality.

fix wrong layouts on Android 15 due to default edge-to-edge feature

---

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/nextcloud/NewsAPI.java

No idea why I added the `@FormUrlEncoded` annotation in the first place. The specs (https://nextcloud.github.io/news/api/api-v1-3/#get-all-feeds) are not expecting it and it causes issues with custom server implementation as mentioned in #1510.
Fix for https://github.com/nextcloud/news-android/issues/1510

remove incorrect FormUrlEncoded annotation

---

News-Android-App/build.gradle
gradle.properties

better to wait for official migration assistant for v36 - even though some libs seem to already require it https://github.com/nextcloud/news-android/pull/1571

downgrade to sdk 35
