nextcloud/news-android

News-Android-App/build.gradle, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java
Also remove a workaround I added previously, but forgot to mention. Fixes #371
=> Use version 3.0.0 of AndroidSlidingUpPanel to fix #371

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/res/layout/fragment_newsreader_list.xml
* Reduce the height of the header to allow more space for the actual content
* Increase the drag margin for the navigation drawer to prevent accidentally starting a star swipe when trying to open the drawer
See discussion in #376
=> (Partial) Fix for some design issues as discussed in #376

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java
CustomTabsService will now unbind correctly onDetroy and not load any connection.
=> Fixed leaked connection from CustomTabsService.

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/SubscriptionExpandableListAdapter.java
=> Switched collapse folder icons.

News-Android-App/build.gradle, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/VersionInfoDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/DownloadChangelogTask.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/view/ChangeLogFileListView.java, News-Android-App/src/main/res/layout/dialog_version_info.xml, News-Android-App/src/main/res/values/colors.xml, News-Android-App/src/main/res/values/strings.xml
Replaced custom changeloglib submodule with gradle dependency for better maintainability.
Code cleanup and minor styling fixes.
=> Replaced changeloglib

News-Android-App/src/main/res/values/strings.xml
@David-Development this should fix https://github.com/nextcloud/news-android/issues/580#issuecomment-335542588 :)
=> Disable app name translation

News-Android-App/src/main/res/values-de-rDE/strings.xml
=> Updated de-rDE (German (Germany)) translation

News-Android-App/src/main/assets/web.css, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/ViewHolder.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/RssItemToHtmlTask.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/FavIconHandler.java, News-Android-App/src/main/res/values/strings.xml, News-Android-App/src/main/res/xml/pref_display.xml
Hi @David-Development, I found a way to scale font size in the webview that looks reasonably elegant to me - let me know what you think!
I will extend the feature to the feed view next.
=> #467 add font size scaling

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/OwnCloudSyncService.java
Background sync didn't work due to immediate exit (destroy) of service (disposable gets cleaned up and sync was interrupted as the main thread returned right away..)
=> fix #696 - no automatic sync 

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java, News-Android-App/src/main/res/values/strings.xml, News-Android-App/src/main/res/xml/pref_about.xml
@David-Development this should fix issue #711 - but wants your eyes&brain
Also: I took the liberty to add a 'report an issue' link to the about-prefs; do you think that's a good idea, considering the capacity we have to actually address incoming requests?
=> Show changelog on tablet

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java, News-Android-App/src/main/res/values-ca/strings.xml, News-Android-App/src/main/res/values-de/strings.xml, News-Android-App/src/main/res/values-lt-rLT/strings.xml
Follow up for #726, otherwise app crashes.
=> update progress on ui thread

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
=> only show unread items if parent folder is ALL_UNREAD_ITEMS

.circleci/config.yml
I needed to upgrade Android Studio & sso library to fix the build.
Tests are not included in this PR since they still are broken (https://circleci.com/gh/Unpublished/news-android/10). Seems related to `robolectric` but I didn't dig deeper here.
=> add CircleCI build integration

.circleci/config.yml, News-Android-App/build.gradle, News-Android-App/src/test/java/de/luhmer/owncloudnewsreader/junit_tests/TestDbTest.java, gradle.properties
Removing the dummy `test` method actually fixes the test...
Otherwise there is a weird [error](https://circleci.com/gh/Unpublished/news-android/73
)
=> update to robolectric 4.2.1, fix unit test and include test in ci

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
Signed-off-by: Unpublished <unpublished@gmx.net>
=> Correctly save and use folder id in instance state

News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/NewsListRecyclerAdapter.java
=> fix location reset of browser by orientation changes

News-Android-App/build.gradle, News-Android-App/src/androidTest/java/de/luhmer/owncloudnewsreader/di/TestApiModule.java, News-Android-App/src/androidTest/java/de/luhmer/owncloudnewsreader/di/TestApiProvider.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogActivity.java, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
Update SSO lib to fix [build failure](https://circleci.com/gh/nextcloud/news-android/108).
Also bump AGP from 3.4.1 to 3.4.2 and gradle from 5.3.1 to 5.5.1
=> Fix build and tests

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/ThemeChooser.java, build.gradle
Fix lint errors caused by update
=> Bump gradle from 3.4.2 to 3.5.0

News-Android-App/build.gradle, News-Android-App/src/androidTest/java/de/luhmer/owncloudnewsreader/di/TestApiProvider.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
=> Update SSO lib to 0.5.0-rc1

News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/PodcastPlaybackService.java
supports "Play/Pause music" so far. As well as the previous and next buttons
=> implement basic voice commands

News-Android-App/src/main/res/layout/subscription_list_item.xml, News-Android-App/src/main/res/layout/subscription_list_sub_item.xml
=> Text in drawer not bold, except of "add new feed" and "settings"

README.md
This might be helpful for detecting problems in the F-Droid build.
=> Display version badges

News-Android-App/build.gradle, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/ThemeChooser.java
=> only request location permission if automatic theme switching is enabled

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/ViewHolder.java
Fixes https://github.com/nextcloud/news-android/issues/786
=> fix android 4.4 xml loading issues of vector drawables

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java
Signed-off-by: David Luhmer <david-dev@live.de>
=> Show feed name in title - fix #846

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/nextcloud/RssItemObservable.java
Fixes https://github.com/nextcloud/news-android/issues/344
Signed-off-by: David Luhmer <david-dev@live.de>
=> fix broken sync of starred articles

CHANGELOG.md, News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/nextcloud/RssItemObservable.java
Signed-off-by: David Luhmer <david-dev@live.de>
=> bump version to 0.9.9.40

News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SyncIntervalSelectorActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/notification/NextcloudNotificationManager.java
Closes https://github.com/nextcloud/news-android/issues/754
=> Optimize notification

News-Android-App/src/main/res/values/strings.xml
=> Use "→" instead of "->" in settings string

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
Split special case for all items to another method.
=> Avoid leaking lazy list cursor

News-Android-App/build.gradle, News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/Constants.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/PodcastFragmentActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/OwnCloudSyncAdapter.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/DatabaseUtils.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/NotificationActionReceiver.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/NotificationActionReceiverDownloadWebPage.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/helper/Search.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/notification/NextcloudNotificationManager.java, News-Android-App/src/main/res/layout/widget_item.xml
- Add notification action "Mark all as read" #911
- Notifications should respect sorting setting #901
- Fix color of date in widget (use material gray)
- Fix OPML parsing issue #909
=> Minor refactorings

News-Android-App/build.gradle, News-Android-App/src/androidTest/java/de/luhmer/owncloudnewsreader/tests/NewsReaderListActivityUiTests.java, News-Android-App/src/androidTest/java/screengrab/ScreenshotTest.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java
=> Fix build after conflict

News-Android-App/build.gradle, News-Android-App/src/main/res/values/strings.xml
=> Remove extra variant and bump some deps

.github/workflows/ci.yml, News-Android-App/proguard-rules.pro, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/widget/WidgetNewsViewsFactory.java
=> Add lint to CI workflow

News-Android-App/build.gradle, News-Android-App/src/dev/res/values/strings.xml, News-Android-App/src/main/AndroidManifest.xml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailImageDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SyncIntervalSelectorActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/adapter/NewsListRecyclerAdapter.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/AccountGeneral.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/OwnCloudSyncAdapter.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/DownloadImagesService.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/services/OwnCloudSyncService.java, News-Android-App/src/main/res/layout/subscription_detail_list_item_card_view.xml, News-Android-App/src/main/res/values/strings.xml, News-Android-App/src/main/res/xml/authenticator.xml, News-Android-App/src/main/res/xml/syncadapter.xml, build.gradle
Only last commit is relevant.
This matches how Nextcloud Android client handles authorities and account types for different build variants.
=> Allow installing dev build next to release build

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListFragment.java, News-Android-App/src/main/res/layout/fragment_newsreader_list.xml, News-Android-App/src/main/res/menu/drawer_menu.xml, News-Android-App/src/main/res/menu/list_footer_menu.xml
Align design more to the other apps. Settings are probably not required that often...
=> Make settings menu item scrollable

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java, News-Android-App/src/main/res/values/strings.xml
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> Add text strings for translation

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/SettingsActivity.java, News-Android-App/src/main/res/values/strings.xml
=> Fix #984 - Remove invalid xml from strings.xml

.github/workflows/FUNDING.yml
to display a native GitHub button to sponsor
=> Add funding.yml

.github/workflows/ci.yml
=> Bump actions/setup-java to 2.1.0

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/LoginDialogActivity.java
=> Preserve cursor position when switching between password visibility modes

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/AddFolderDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/FolderOptionsDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/authentication/OwnCloudSyncAdapter.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/di/AppComponent.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/nextcloud/NewsAPI.java, News-Android-App/src/main/res/drawable/ic_baseline_create_new_folder_24_black.xml, News-Android-App/src/main/res/drawable/ic_baseline_folder_24.xml, News-Android-App/src/main/res/layout/fragment_dialog_add_folder.xml, News-Android-App/src/main/res/layout/fragment_dialog_folderoptions.xml, News-Android-App/src/main/res/menu/list_footer_menu.xml, News-Android-App/src/main/res/values/strings.xml
Implemented features and fixes:
Close #778
=> Folder management

CHANGELOG.md, News-Android-App/build.gradle, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java, build.gradle
Signed-off-by: David Luhmer <david-dev@live.de>
=> fix several app crashed / update to 0.9.9.73

News-Android-App/src/main/res/values/strings.xml
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
=> l10n: Fixed grammar

News-Android-App/build.gradle, build.gradle
Prevent attacks like #1109 via abandoned domain names.
=> Only resolve nextcloud sso dep via jitpack

News-Android-App/proguard-rules.pro
- keepnames is handled via dontobfuscate
- OkHttp bundles rules
=> Remove OkHttp rules and keepnames

README.md
https://help.nextcloud.com/t/transifex-announcement-web-applications-domain-change/159445
**Open Question:** @tobiasKaminsky @AndyScherzinger do we need also to adjust the `host` property in `.tx/config` for automated translations?
=> fix(i18n): Adjust links to transifex

.github/workflows/codeql.yml, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java
Should fix #1147
Please verify @stefan-niedermann
=> Wrap list of folders in ArrayList to prevent crash

CHANGELOG.md, News-Android-App/src/main/assets/web.css
=> dont format spans as display: block (fix for #1085)

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java
=> Fix starred items not obeying sort order

News-Android-App/src/main/AndroidManifest.xml
See [Android Dev](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture) for more information
=> Enable support for predictive back gestures

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/RssItemToHtmlTask.java
|Before|After|
|----|---|
| <img src="https://github.com/nextcloud/news-android/assets/18418792/0bbcfe94-2d49-4d46-91fc-0f131db2c303" width="300px"> | <img src="https://github.com/nextcloud/news-android/assets/18418792/7a6e0061-5278-4b07-b99b-dc4fc3b295dd" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/24368336/269779517-83726912-8ac5-4270-99a2-3a05e48fd0b0.png" width="300px" /> | <img src="https://github.com/nextcloud/news-android/assets/18418792/e2878158-40f4-4359-bc1e-c1c5d9c6da2e" width="300px" /> |
Everything inside `<pre> ... </pre>` will keep their formatting because that is what pre-tags are for.
This fixes #1270
=> Fix weird formatting in articles

News-Android-App/src/main/AndroidManifest.xml
=> Fix app crashing when streaming or downloading podcasts

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/ListView/SubscriptionExpandableListAdapter.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListFragment.java
related to https://github.com/nextcloud/news-android/issues/1285 - however I couldn't identify the exact issue just yet.
=> simplify reload of sidebar

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/RssItemToHtmlTask.java, News-Android-App/src/test/java/de/luhmer/owncloudnewsreader/asynctasks/RssItemToHtmlTaskTest.kt
=> Only replace first occurrence of pre block pattern

News-Android-App/src/main/assets/web.css
| Before | After |
| ------ | ------ |
| <img src="https://github.com/user-attachments/assets/3d0bbde5-421d-4d0b-909d-511ab077e7ae" width="300px" /> | <img src="https://github.com/user-attachments/assets/26259122-a61b-41bc-af6f-cb03959c9d97" width="300px" />
=> add padding for list css

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsDetailFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/async_tasks/RssItemToHtmlTask.java
Closes https://github.com/nextcloud/news-android/issues/1490
=> set zoom of webview content via webview textZoom feature

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderDetailFragment.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java, News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/database/DatabaseConnectionOrm.java, News-Android-App/src/main/res/values/strings.xml
=> Show snackbar after batch marking items as read

News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewFeedActivity.java
fix for https://github.com/nextcloud/news-android/issues/1576
=> remove unused permission check
